version: '3.9'

networks:
  microservices-net:
    driver: bridge

volumes:
  rabbitmq-data:
  postgres-data:
  prometheus-data:
  grafana-data:
  elasticsearch-data:


services:

  # ── Infrastructure ─────────────────────────────────────────────────────────

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # Management UI (guest/guest)
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - microservices-net
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Str0ngP@ssword!"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - microservices-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - microservices-net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - microservices-net

  jaeger:
    image: jaegertracing/all-in-one:1.58
    container_name: jaeger
    ports:
      - "6831:6831/udp" # Jaeger agent
      - "16686:16686" # Jaeger UI
    networks:
      - microservices-net

  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: prometheus
    volumes:
      - ./infrastructure/docker/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - microservices-net

  grafana:
    image: grafana/grafana:11.1.0
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin"
    networks:
      - microservices-net
    depends_on:
      - prometheus

  # ── Services ───────────────────────────────────────────────────────────────

  user-service:
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile.usersvc
    container_name: user-service
    ports:
      - "5001:5001" # REST
      - "5101:5101" # gRPC
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__Host=rabbitmq
      - ConnectionStrings__UserDb=Host=postgres;Port=5432;Database=UserDb;Username=postgres;Password=Str0ngP@ssword!
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - microservices-net

  order-service:
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile.ordersvc
    container_name: order-service
    ports:
      - "5002:5002" # REST
      - "5102:5102" # gRPC
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__Host=rabbitmq
      - ConnectionStrings__OrderDb=Host=postgres;Port=5432;Database=OrderDb;Username=postgres;Password=Str0ngP@ssword!
      - GrpcClients__UserService=http://user-service:5101
    depends_on:
      user-service:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - microservices-net

  payment-service:
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile.paymentsvc
    container_name: payment-service
    ports:
      - "5003:5003"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__Host=rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - microservices-net

  web-bff:
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile.webbff
    container_name: web-bff
    ports:
      - "5010:5010"
    environment:
      - Services__UserService=http://user-service:5001
      - Services__OrderService=http://order-service:5002
    depends_on:
      - user-service
      - order-service
    networks:
      - microservices-net

  api-gateway:
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile.gateway
    container_name: api-gateway
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - user-service
      - order-service
      - web-bff
    networks:
      - microservices-net
