FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY Directory.Build.props .
COPY building-blocks/ building-blocks/
COPY bff/WebBff/ bff/WebBff/

RUN dotnet restore bff/WebBff/WebBff.csproj
RUN dotnet publish bff/WebBff/WebBff.csproj \
    -c Release -o /app/out --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/out .
EXPOSE 5010
ENTRYPOINT ["dotnet", "WebBff.dll"]
