# Kubernetes External Secrets Operator (ESO) configuration for HashiCorp Vault
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://vault.microservices.svc.cluster.local:8200" # K8s internal DNS to Vault
      path: "secret"
      version: "v2"
      auth:
        # For simplicity in dev, using a static token. 
        # In PROD, use Kubernetes Service Account (JWT) auth method in Vault.
        tokenSecretRef:
          name: vault-token-secret
          key: token
          namespace: external-secrets

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-secrets-sync
  namespace: microservices
spec:
  refreshInterval: "15s" # Syncs every 15 seconds from Vault
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: db-secrets # Creates the standard K8s Secret named 'db-secrets' that our Deployments expect
    creationPolicy: Owner
  data:
    - secretKey: user-db-connection
      remoteRef:
        key: microservices/database # Path in Vault: secret/data/microservices/database
        property: user-db-connection
    - secretKey: order-db-connection
      remoteRef:
        key: microservices/database
        property: order-db-connection
